# ==========================
#
# THIS IS A GENERATED FILE. Don't modify this file.
#
# Modify file in .github/jsTemplates/dependabot.yml.ts
#
# ==========================

version: 2
updates:
  - directory: /
    schedule:
      interval: daily
      time: '23:30'
      timezone: Asia/Kolkata
    open-pull-requests-limit: 5
    target-branch: develop
    assignees:
      - libinvarghese
    allow:
      - dependency-type: direct
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    package-ecosystem: npm
  - directory: /
    schedule:
      interval: daily
      time: '23:30'
      timezone: Asia/Kolkata
    open-pull-requests-limit: 5
    target-branch: develop
    assignees:
      - libinvarghese
    allow:
      - dependency-type: direct
    commit-message:
      prefix: chore
      prefix-development: chore
      include: scope
    package-ecosystem: pip
  - directory: /.github/dependabotGithubActions/
    schedule:
      interval: daily
      time: '23:30'
      timezone: Asia/Kolkata
    open-pull-requests-limit: 5
    target-branch: develop
    assignees:
      - libinvarghese
    commit-message:
      prefix: chore
      prefix-development: chore
      include: scope
    package-ecosystem: github-actions
