---
version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      time: '23:30'
      timezone: Asia/Kolkata
    open-pull-requests-limit: 5
    target-branch: develop
    reviewers:
      - libinvarghese
    assignees:
      - libinvarghese
    allow:
      - dependency-type: direct
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
      time: '23:30'
      timezone: Asia/Kolkata
    open-pull-requests-limit: 5
    target-branch: develop
    reviewers:
      - libinvarghese
    assignees:
      - libinvarghese
    allow:
      - dependency-type: direct
    commit-message:
      prefix: chore
      prefix-development: chore
      include: scope
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: '23:30'
      timezone: Asia/Kolkata
    open-pull-requests-limit: 5
    target-branch: develop
    reviewers:
      - libinvarghese
    assignees:
      - libinvarghese
    commit-message:
      prefix: chore
      prefix-development: chore
      include: scope
...
