---
extends: default

ignore: |
  /dist/*
  /node_modules/
  /coverage/
  /.nyc_output/
  /.github/workflows/
  /.github/dependabot.yml
  /.github/dependabotGithubActions/

rules:
  comments: enable
  comments-indentation: enable
  document-end: enable
  document-start: enable
  empty-lines:
    max: 1
  line-length:
    max: 120
  indentation:
    spaces: 2
    check-multi-line-strings: true
  quoted-strings:
    quote-type: single
    required: only-when-needed

...
