---
version: 1
update_configs:
  - package_manager: javascript
    directory: /
    update_schedule: live
    target_branch: develop
    default_reviewers:
      - libinvarghese
    default_assignees:
      - libinvarghese
    allowed_updates:
      - match:
          dependency_type: direct
          update_type: all
      - match:
          dependency_type: all
          update_type: security
    version_requirement_updates: auto
    commit_message:
      prefix: fix
      prefix_development: chore
      include_scope: true
    automerged_updates:
      - match:
          dependency_type: all
          update_type: all
...
