---
# Merge me!
name: automerge-dependabot

# yamllint disable-line rule:truthy
on:
  pull_request:
    types:
      - edited
      - labeled
      - opened
      - ready_for_review
      - reopened
      - synchronize
      - unlabeled
      - unlocked
    branches:
      - master
      - develop

jobs:
  merge-me:
    name: automerge-dependabot
    runs-on: ubuntu-latest
    steps:
      - name: Wait for commitlint
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-commitlint
        with:
          token: ${{ secrets.REPO_ACCESS }}
          timeoutSeconds: 180
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          checkName: commitlint
      - name: Exit when commitlint workflow has failed
        if:
          steps.wait-for-commitlint.outputs.conclusion != 'success' && steps.wait-for-commitlint.outputs.conclusion !=
          'timed_out'
        run: |
          exit 1
      - name: Wait for lint
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-lint
        with:
          token: ${{ secrets.REPO_ACCESS }}
          timeoutSeconds: 180
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          checkName: lint
      - name: Exit when lint workflow has failed
        if: steps.wait-for-lint.outputs.conclusion != 'success' && steps.wait-for-lint.outputs.conclusion != 'timed_out'
        run: |
          exit 1
      - name: Wait for build
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-build
        with:
          token: ${{ secrets.REPO_ACCESS }}
          timeoutSeconds: 180
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          # yamllint disable-line rule:quoted-strings
          checkName: 'build (12.x)'
      - name: Exit when build workflow has failed
        if:
          steps.wait-for-build.outputs.conclusion != 'success' && steps.wait-for-build.outputs.conclusion != 'timed_out'
        run: |
          exit 1
      - name: Wait for test
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-test
        with:
          token: ${{ secrets.REPO_ACCESS }}
          timeoutSeconds: 180
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          # yamllint disable-line rule:quoted-strings
          checkName: 'test (12.x)'
      - name: Exit when test workflow has failed
        if: steps.wait-for-test.outputs.conclusion != 'success' && steps.wait-for-test.outputs.conclusion != 'timed_out'
        run: |
          exit 1
      - name: Merge me!
        uses: ridedott/merge-me-action@v1.3.11
        with:
          GITHUB_LOGIN: dependabot[bot]
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS }}
          MERGE_METHOD: MERGE
...
