# ==========================
#
# THIS IS A GENERATED FILE. Don't modify this file.
#
# Modify file in .github/jsTemplates/workflows/automerge.yml.ts
#
# ==========================

name: automerge-dependabot
'on':
  pull_request:
    types:
      - edited
      - reopened
      - synchronize
      - labeled
    branches:
      - develop
jobs:
  pre-automerge-bot:
    outputs:
      status: '${{ steps.check-author.conclusion }}'
    runs-on: ubuntu-latest
    steps:
      - name: 'Check if author is dependabot[bot]'
        id: check-author
        if: 'github.event.pull_request.user.login != ''dependabot[bot]'''
        run: |-
          echo Skip! Pull request created by ${{ github.event.pull_request.user.login }} not dependabot[bot]
          exit 0
  github-action:
    needs:
      - pre-automerge-bot
    if: needs.pre-automerge-bot.outputs.status != 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Dump github.event.pull_request.labels.*.name context
        env:
          PULL_REQUEST_LABELS_CONTEXT: '${{ toJson(github.event.pull_request.labels.*.name) }}'
        run: echo "$PULL_REQUEST_LABELS_CONTEXT"
      - name: Update .github/jsTemplates/utils/dependencies.ts
        if: 'contains( github.event.pull_request.labels.*.name, ''github_actions'')'
        run: >
          npx ts-node scripts/githubActionsDepGen.ts

          git add .github/jsTemplates/utils/dependencies.ts

          npm run js2yaml

          git diff --quiet || echo 'Files pending to stage!' || false &&   git diff --staged --quiet && echo 'No changes
          to commit' ||   git commit --no-verify -m 'chore(deps): bump dependency in template'
  automerge-dependabot:
    needs:
      - github-action
    runs-on: ubuntu-latest
    steps:
      - name: Wait for commitlint
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-Commitlint
        with:
          token: '${{ secrets.REPO_ACCESS }}'
          checkName: commitlint
          ref: '${{ github.event.pull_request.head.sha || github.sha }}'
          timeoutSeconds: 180
      - name: Exit when commitlint workflow has failed
        if: >-
          steps.wait-for-Commitlint.outputs.conclusion != 'success' && steps.wait-for-Commitlint.outputs.conclusion !=
          'timed_out'
        run: |
          exit 1
      - name: Wait for lint
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-Lint
        with:
          token: '${{ secrets.REPO_ACCESS }}'
          checkName: lint
          ref: '${{ github.event.pull_request.head.sha || github.sha }}'
          timeoutSeconds: 180
      - name: Exit when lint workflow has failed
        if: steps.wait-for-Lint.outputs.conclusion != 'success' && steps.wait-for-Lint.outputs.conclusion != 'timed_out'
        run: |
          exit 1
      - name: Wait for build (12.x)
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-Build12X
        with:
          token: '${{ secrets.REPO_ACCESS }}'
          checkName: build (12.x)
          ref: '${{ github.event.pull_request.head.sha || github.sha }}'
          timeoutSeconds: 180
      - name: Exit when build (12.x) workflow has failed
        if: >-
          steps.wait-for-Build12X.outputs.conclusion != 'success' && steps.wait-for-Build12X.outputs.conclusion !=
          'timed_out'
        run: |
          exit 1
      - name: Wait for test (12.x)
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-Test12X
        with:
          token: '${{ secrets.REPO_ACCESS }}'
          checkName: test (12.x)
          ref: '${{ github.event.pull_request.head.sha || github.sha }}'
          timeoutSeconds: 180
      - name: Exit when test (12.x) workflow has failed
        if: >-
          steps.wait-for-Test12X.outputs.conclusion != 'success' && steps.wait-for-Test12X.outputs.conclusion !=
          'timed_out'
        run: |
          exit 1
      - name: Merge me!
        uses: libinvarghese/merge-me-action@v1
        with:
          GITHUB_LOGIN: 'dependabot[bot]'
          GITHUB_TOKEN: '${{ secrets.REPO_ACCESS }}'
          MERGE_METHOD: MERGE
