# ==========================
#
# THIS IS A GENERATED FILE. Don't modify this file.
#
# Modify file in .github/jsTemplates/workflows/commitlint.yml.ts
#
# ==========================

name: commitlint
'on':
  pull_request:
    branches:
      - develop
      - master
jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'Git fetch Base - ${{ github.base_ref }}'
        run: |
          git fetch --no-tags --prune --progress --no-recurse-submodules origin +$BASE:$BASE
        env:
          BASE: '${{ github.base_ref }}'
      - name: Use Node.js 12.x
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12.x
      - name: Get npm cache directory
        id: get-npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - name: Cache Node.js modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: '${{ steps.get-npm-cache.outputs.dir }}'
          key: '${{ runner.OS }}-${{ env.cache-name }}-${{ hashFiles(''**/package-lock.json'') }}'
          restore-keys: |
            ${{ runner.OS }}-${{ env.cache-name }}-
            ${{ runner.OS }}-
      - name: Cache Project node_modules
        uses: actions/cache@v2
        id: cache-project-node-modules
        env:
          cache-name: cache-project-node-modules
        with:
          path: node_modules
          key: '${{ runner.OS }}-${{ env.cache-name }}-${{ github.repository }}-${{ hashFiles(''**/package-lock.json'') }}'
      - name: Install Dependencies
        if: steps.cache-project-node-modules.outputs.cache-hit != 'true'
        run: npm ci
      - name: 'Commit Lint from ${{ github.base_ref }}'
        run: npx commitlint -g .commitlintrc.ci.js --from $(git merge-base --fork-point $BASE) --verbose
        env:
          BASE: '${{ github.base_ref }}'
