---

# This workflow will do a clean install of node dependencies, build the source code and run linter
# For more information
# see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: debug

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - 'keep/ci-debug'

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Get pip version
        id: pip-cache
        run: |
          pip --version
          pip cache dir
          echo "::set-output name=dir::$(pip cache dir)"
      - name: Read pip cache dir
        run: |
          echo ${{ steps.pip-cache.outputs.dir }}
...
