---

# This workflow will do a clean install of node dependencies, build the source code and run linter
# For more information
# see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: lint-all

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - keep/ci-debug

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Dump workflow name & job name
        run: |
          echo ${{ github.workflow }} / ${{ github.job }}

...
