# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: On Push CI

on:
  push:
    branches:
      - master

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm ci
    - run: npm run coverage
      env:
        CI: true
    - name: Codecov
      uses: codecov/codecov-action@v1.0.6
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
