# ==========================
#
# THIS IS A GENERATED FILE. Don't modify this file.
#
# Modify file in .github/jsTemplates/workflows/security-update.yml.ts
#
# ==========================

name: security-update
'on':
  pull_request:
    types:
      - opened
    branches:
      - master
jobs:
  cancel-not-dependabot:
    if: 'github.event.pull_request.user.login == ''dependabot[bot]'''
    steps:
      - run: 'echo Pull request created by ${{ github.event.pull_request.user.login }} is dependabot[bot]'
  pr-update-base:
    needs:
      - cancel-not-dependabot
    runs-on: ubuntu-latest
    steps:
      - uses: a-b-r-o-w-n/check-base-branch-action@v1
        with:
          repo-token: '${{ secrets.REPO_ACCESS }}'
          protectedBranches: master
          defaultBranch: develop
          update-branch: true
